export default {
//  {
    "data": [
      {
        "id": 183086,
        "common_name": "European mountain ash",
        "slug": "sorbus-aucuparia",
        "scientific_name": "Sorbus aucuparia",
        "year": 1753,
        "bibliography": "Sp. Pl.: 477 (1753)",
        "author": "L.",
        "status": "accepted",
        "rank": "species",
        "family_common_name": "Rose family",
        "genus_id": 677,
        "image_url": "https://bs.floristic.org/image/o/63073d2fbf45b90701279405ecc2eec0272906ed",
        "synonyms": [
          "Pyrenia aucuparia",
          "Aucuparia silvestris",
          "Pyrus lanuginosa",
          "Sorbus altaica",
          "Sorbus lanuginosa",
          "Sorbus cordata",
          "Sorbus subserrata",
          "Sorbus anadyrensis",
          "Sorbus boissieri",
          "Sorbus caucasigena",
          "Mespilus aucuparia",
          "Sorbus monticola",
          "Pyrus boissieri"
        ],
        "genus": "Sorbus",
        "family": "Rosaceae",
        "links": {
          "self": "/api/v1/species/sorbus-aucuparia",
          "plant": "/api/v1/plants/sorbus-aucuparia",
          "genus": "/api/v1/genus/sorbus"
        }
      },
      {
        "id": 1164724,
        "common_name": "Christmastree",
        "slug": "abies-alba",
        "scientific_name": "Abies alba",
        "year": 1756,
        "bibliography": "Gard. Dict. ed. 7: n.º 1 (1756)",
        "author": "Mill.",
        "status": "accepted",
        "rank": "species",
        "family_common_name": "Pine family",
        "genus_id": 4,
        "image_url": "https://bs.floristic.org/image/o/7928c21ee9fdc5ffa423501d3ba54084247cf9a9",
        "synonyms": [
          "Abies nobilis",
          "Pinus heterophylla",
          "Pinus abies",
          "Abies pectinata",
          "Pinus picea",
          "Abies taxifolia",
          "Abies minor",
          "Abies picea",
          "Abies abies",
          "Abies chlorocarpa",
          "Abies pardei",
          "Picea pectinata",
          "Pinus pectinata",
          "Pinus baldensis",
          "Picea tenuifolia",
          "Abies alba var. pardei",
          "Peuce abies",
          "Abies alba subsp. pardei",
          "Picea metensis",
          "Picea rinzi",
          "Abies argentea",
          "Abies candicans",
          "Picea pyramidalis",
          "Abies baldensis",
          "Abies vulgaris",
          "Picea kukunaria",
          "Abies alba subsp. apennina",
          "Abies metensis",
          "Pinus lucida",
          "Abies miniata"
        ],
        "genus": "Abies",
        "family": "Pinaceae",
        "links": {
          "self": "/api/v1/species/abies-alba",
          "plant": "/api/v1/plants/abies-alba",
          "genus": "/api/v1/genus/abies"
        }
      },
      {
        "id": 188325,
        "common_name": "Spreading hedgeparsley",
        "slug": "torilis-arvensis",
        "scientific_name": "Torilis arvensis",
        "year": 1821,
        "bibliography": "Enum. Hort. Berol. Alt. 1: 265 (1821)",
        "author": "(Huds.) Link",
        "status": "accepted",
        "rank": "species",
        "family_common_name": "Carrot family",
        "genus_id": 6637,
        "image_url": "https://bs.floristic.org/image/o/a95a92e4a3c02b87f8ecc8c7f6886cc52bec31da",
        "synonyms": [
          "Caucalis arvensis",
          "Torilis arvensis subsp. heterophylla",
          "Scandix infesta",
          "Caucalis infesta",
          "Torilis infesta",
          "Caucalis helvetica",
          "Caucalis divaricata",
          "Lappularia neglecta",
          "Tordylium segetum",
          "Caucalis segetum",
          "Torilis chlorocarpa",
          "Ozotrix helvetica",
          "Caucalis aspersa",
          "Torilis friedrichsthalii",
          "Lappularia infesta",
          "Torilis divaricata",
          "Torilis helvetica",
          "Caucalis angustifolia",
          "Caucalis aglochis",
          "Anthriscus arvensis",
          "Daucus infestus",
          "Caucalis segetalis",
          "Torilis aglochis"
        ],
        "genus": "Torilis",
        "family": "Apiaceae",
        "links": {
          "self": "/api/v1/species/torilis-arvensis",
          "plant": "/api/v1/plants/torilis-arvensis",
          "genus": "/api/v1/genus/torilis"
        }
      },
      {
        "id": 137810,
        "common_name": "White ash",
        "slug": "fraxinus-americana",
        "scientific_name": "Fraxinus americana",
        "year": 1753,
        "bibliography": "Sp. Pl.: 1057 (1753)",
        "author": "L.",
        "status": "accepted",
        "rank": "species",
        "family_common_name": "Olive family",
        "genus_id": 3064,
        "image_url": "https://bs.floristic.org/image/o/ac78a828d9d65c2c27ff47716488f0ceda6b94f0",
        "synonyms": [
          "Fraxinus americana var. biltmoreana",
          "Fraxinus americana var. crassifolia",
          "Fraxinus americana var. curtissii",
          "Fraxinus americana var. microcarpa",
          "Fraxinus biltmoreana",
          "Fraxinus americana f. iodocarpa",
          "Fraxinus americana var. epiptera",
          "Calycomelia alba",
          "Fraxinus americana f. barrii",
          "Calycomelia pistaciifolia",
          "Aplilia macrophyla",
          "Fraxinus americana subsp. biltmoreana",
          "Calycomelia biltmoreana",
          "Fraxinus glauca",
          "Fraxinus americana var. ascidiata",
          "Calycomelia americana",
          "Fraxinus novae-angliae",
          "Fraxinus americana f. acuminata",
          "Leptalix grandifolia",
          "Leptalix epiptera",
          "Fraxinus villosa",
          "Leptalix alba",
          "Ornus americana",
          "Fraxinus juglandifolia",
          "Fraxinus macrophylla",
          "Fraxinus discolor",
          "Fraxinus biltmoreana var. subcoriacea",
          "Fraxinus americana var. longifolia",
          "Calycomelia acuminata",
          "Calycomelia viridis",
          "Leptalix viridis",
          "Fraxinus americana f. ascidiata",
          "Fraxinus epiptera",
          "Fraxinus americana var. subcoriacea",
          "Fraxinus alba",
          "Fraxinus americana subsp. typicum",
          "Fraxinus acuminata",
          "Fraxinus pubescens var. longifolia",
          "Fraxinoides alba",
          "Fraxinus nigra var. juglandifolia",
          "Fraxinus curtissii",
          "Leptalix glauca",
          "Leptalix juglandifolia",
          "Fraxinus americana f. lasiophylla",
          "Calycomelia epiptera",
          "Calycomelia juglandifolia",
          "Fraxinus pennsylvanica subsp. novae-angliae",
          "Ornanthes americana",
          "Fraxinus canadensis",
          "Leptalix acuminata",
          "Fraxinus americana subsp. novae-angliae",
          "Fraxinus albicans",
          "Fraxinus americana var. juglandifolia"
        ],
        "genus": "Fraxinus",
        "family": "Oleaceae",
        "links": {
          "self": "/api/v1/species/fraxinus-americana",
          "plant": "/api/v1/plants/fraxinus-americana",
          "genus": "/api/v1/genus/fraxinus"
        }
      },
      {
        "id": 116854,
        "common_name": "Clustered field sedge",
        "slug": "carex-praegracilis",
        "scientific_name": "Carex praegracilis",
        "year": 1884,
        "bibliography": "Bot. Gaz. 9: 87 (1884)",
        "author": "W.Boott",
        "status": "accepted",
        "rank": "species",
        "family_common_name": "Sedge family",
        "genus_id": 1462,
        "image_url": "http://d2seqvvyy3b8p2.cloudfront.net/ca3ed9f8232591f0c50dd1b9d587bdd0.jpg",
        "synonyms": [
          "Carex camporum",
          "Carex sartwellii var. occidentalis",
          "Carex alterna",
          "Carex marcida f. alterna",
          "Carex gayana var. hyalina",
          "Carex marcida var. alterna",
          "Carex marcida f. debilis",
          "Carex marcida",
          "Carex marcida var. debilis",
          "Carex latebrosa"
        ],
        "genus": "Carex",
        "family": "Cyperaceae",
        "links": {
          "self": "/api/v1/species/carex-praegracilis",
          "plant": "/api/v1/plants/carex-praegracilis",
          "genus": "/api/v1/genus/carex"
        }
      },
      {
        "id": 273225,
        "common_name": null,
        "slug": "senecio-gamolepis",
        "scientific_name": "Senecio gamolepis",
        "year": 1955,
        "bibliography": "Notas Mus. La Plata, Bot. 18(89): 222 (1955)",
        "author": "Cabrera",
        "status": "accepted",
        "rank": "species",
        "family_common_name": "Aster family",
        "genus_id": 669,
        "image_url": null,
        "synonyms": [],
        "genus": "Senecio",
        "family": "Asteraceae",
        "links": {
          "self": "/api/v1/species/senecio-gamolepis",
          "plant": "/api/v1/plants/senecio-gamolepis",
          "genus": "/api/v1/genus/senecio"
        }
      }
    ],
  }
//   }